 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8900/ (Press CTRL+C to quit)
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8900/ (Press CTRL+C to quit)
47.31.203.13 - - [17/Jan/2021 20:25:51] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.203.13 - - [17/Jan/2021 20:25:53] "[37mPOST /issue HTTP/1.1[0m" 200 -
[2021-01-17 20:30:09,436] ERROR in app: Exception on /book_info [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 44, in book_info
    "fine_rem": cal_fine(i["issued_date"]),
  File "main.py", line 20, in cal_fine
    diff = datetime.date.today() - datetime.date(int(start[0]),int(start[1]),int(start[2]))
ValueError: invalid literal for int() with base 10: ''
47.31.203.13 - - [17/Jan/2021 20:30:09] "[35m[1mPOST /book_info HTTP/1.1[0m" 500 -
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8900/ (Press CTRL+C to quit)
47.31.203.13 - - [17/Jan/2021 20:39:58] "[37mPOST /return_ HTTP/1.1[0m" 200 -
47.31.203.13 - - [17/Jan/2021 20:40:27] "[37mPOST /book_info HTTP/1.1[0m" 200 -
47.31.203.13 - - [17/Jan/2021 20:40:44] "[37mPOST /return_ HTTP/1.1[0m" 200 -
47.31.203.13 - - [17/Jan/2021 20:41:10] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.203.13 - - [17/Jan/2021 20:41:31] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.203.13 - - [17/Jan/2021 20:42:37] "[37mPOST /book_info HTTP/1.1[0m" 200 -
47.31.203.13 - - [17/Jan/2021 20:42:38] "[37mPOST /return_ HTTP/1.1[0m" 200 -
106.214.226.208 - - [17/Jan/2021 20:44:26] "[37mPOST /book_info HTTP/1.1[0m" 200 -
[2021-01-17 20:45:03,932] ERROR in app: Exception on /book_info [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 44, in book_info
    "fine_rem": cal_fine(i["issued_date"]),
  File "main.py", line 20, in cal_fine
    diff = datetime.date.today() - datetime.date(int(start[0]),int(start[1]),int(start[2]))
ValueError: invalid literal for int() with base 10: ''
106.214.226.208 - - [17/Jan/2021 20:45:03] "[35m[1mPOST /book_info HTTP/1.1[0m" 500 -
[2021-01-17 20:45:15,599] ERROR in app: Exception on /book_info [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 44, in book_info
    "fine_rem": cal_fine(i["issued_date"]),
  File "main.py", line 20, in cal_fine
    diff = datetime.date.today() - datetime.date(int(start[0]),int(start[1]),int(start[2]))
ValueError: invalid literal for int() with base 10: ''
47.31.203.13 - - [17/Jan/2021 20:45:15] "[35m[1mPOST /book_info HTTP/1.1[0m" 500 -
47.31.203.13 - - [17/Jan/2021 20:45:17] "[37mPOST /return_ HTTP/1.1[0m" 200 -
47.31.203.13 - - [17/Jan/2021 20:45:36] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.203.13 - - [17/Jan/2021 20:45:44] "[37mPOST /book_info HTTP/1.1[0m" 200 -
106.214.226.208 - - [17/Jan/2021 20:46:03] "[37mPOST /book_info HTTP/1.1[0m" 200 -
47.31.203.13 - - [17/Jan/2021 20:46:07] "[37mPOST /return_ HTTP/1.1[0m" 200 -
106.214.226.208 - - [17/Jan/2021 20:46:09] "[37mPOST /return_ HTTP/1.1[0m" 200 -
[2021-01-17 20:46:29,586] ERROR in app: Exception on /book_info [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 44, in book_info
    "fine_rem": cal_fine(i["issued_date"]),
  File "main.py", line 20, in cal_fine
    diff = datetime.date.today() - datetime.date(int(start[0]),int(start[1]),int(start[2]))
ValueError: invalid literal for int() with base 10: ''
47.31.203.13 - - [17/Jan/2021 20:46:29] "[35m[1mPOST /book_info HTTP/1.1[0m" 500 -
47.31.203.13 - - [17/Jan/2021 20:46:48] "[37mPOST /return_ HTTP/1.1[0m" 200 -
[2021-01-17 20:47:06,441] ERROR in app: Exception on /book_info [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 44, in book_info
    "fine_rem": cal_fine(i["issued_date"]),
  File "main.py", line 20, in cal_fine
    diff = datetime.date.today() - datetime.date(int(start[0]),int(start[1]),int(start[2]))
ValueError: invalid literal for int() with base 10: ''
106.214.226.208 - - [17/Jan/2021 20:47:06] "[35m[1mPOST /book_info HTTP/1.1[0m" 500 -
106.214.226.208 - - [17/Jan/2021 20:47:26] "[37mPOST /issue HTTP/1.1[0m" 200 -
106.214.226.208 - - [17/Jan/2021 20:47:53] "[37mPOST /book_info HTTP/1.1[0m" 200 -
106.214.226.208 - - [17/Jan/2021 22:04:00] "[37mGET /just_4_test_baby HTTP/1.1[0m" 200 -
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8900/ (Press CTRL+C to quit)
47.31.253.171 - - [18/Jan/2021 06:11:47] "[37mPOST /new_book HTTP/1.1[0m" 200 -
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8900/ (Press CTRL+C to quit)
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8900/ (Press CTRL+C to quit)
47.31.253.171 - - [18/Jan/2021 06:40:31] "[37mPOST /new_book HTTP/1.1[0m" 200 -
47.31.253.171 - - [18/Jan/2021 06:41:43] "[37mPOST /new_book HTTP/1.1[0m" 200 -
47.31.253.171 - - [18/Jan/2021 06:42:22] "[37mPOST /new_book HTTP/1.1[0m" 200 -
47.31.253.171 - - [18/Jan/2021 06:45:04] "[37mPOST /new_book HTTP/1.1[0m" 200 -
47.9.92.197 - - [18/Jan/2021 07:45:55] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
47.30.220.69 - - [18/Jan/2021 08:21:45] "[37mPOST /new_book HTTP/1.1[0m" 200 -
47.30.220.69 - - [18/Jan/2021 08:22:24] "[37mPOST /new_book HTTP/1.1[0m" 200 -
47.31.240.37 - - [18/Jan/2021 08:24:21] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.240.37 - - [18/Jan/2021 08:24:33] "[37mPOST /book_info HTTP/1.1[0m" 200 -
47.31.240.37 - - [18/Jan/2021 08:24:42] "[37mPOST /return_ HTTP/1.1[0m" 200 -
47.31.240.37 - - [18/Jan/2021 08:25:04] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.240.37 - - [18/Jan/2021 08:25:11] "[37mPOST /book_info HTTP/1.1[0m" 200 -
47.31.240.37 - - [18/Jan/2021 08:25:28] "[37mPOST /return_ HTTP/1.1[0m" 200 -
[2021-01-18 08:25:34,997] ERROR in app: Exception on /book_info [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 58, in book_info
    "fine_rem": cal_fine(i["issued_date"]),
  File "main.py", line 18, in cal_fine
    diff = datetime.date.today() - datetime.date(int(start[0]),int(start[1]),int(start[2]))
ValueError: invalid literal for int() with base 10: ''
47.31.240.37 - - [18/Jan/2021 08:25:34] "[35m[1mPOST /book_info HTTP/1.1[0m" 500 -
47.30.220.69 - - [18/Jan/2021 08:26:25] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.229.2 - - [18/Jan/2021 10:00:01] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.229.2 - - [18/Jan/2021 10:00:13] "[37mPOST /book_info HTTP/1.1[0m" 200 -
47.31.229.2 - - [18/Jan/2021 10:00:26] "[37mPOST /book_info HTTP/1.1[0m" 200 -
47.31.229.2 - - [18/Jan/2021 10:00:40] "[37mPOST /return_ HTTP/1.1[0m" 200 -
106.202.72.57 - - [18/Jan/2021 10:15:46] "[37mPOST /issue HTTP/1.1[0m" 200 -
106.202.72.57 - - [18/Jan/2021 10:16:39] "[37mPOST /issue HTTP/1.1[0m" 200 -
106.202.72.57 - - [18/Jan/2021 10:17:05] "[37mPOST /issue HTTP/1.1[0m" 200 -
106.202.72.57 - - [18/Jan/2021 10:18:02] "[37mPOST /issue HTTP/1.1[0m" 200 -
106.202.72.57 - - [18/Jan/2021 10:18:35] "[37mPOST /issue HTTP/1.1[0m" 200 -
106.202.72.57 - - [18/Jan/2021 10:21:22] "[37mPOST /new_book HTTP/1.1[0m" 200 -
106.202.72.57 - - [18/Jan/2021 10:22:42] "[37mPOST /new_book HTTP/1.1[0m" 200 -
106.202.72.57 - - [18/Jan/2021 10:23:55] "[37mPOST /new_book HTTP/1.1[0m" 200 -
106.202.72.57 - - [18/Jan/2021 10:24:41] "[37mPOST /new_book HTTP/1.1[0m" 200 -
[2021-01-18 10:30:11,602] ERROR in app: Exception on /book_info [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 58, in book_info
    "fine_rem": cal_fine(i["issued_date"]),
  File "main.py", line 18, in cal_fine
    diff = datetime.date.today() - datetime.date(int(start[0]),int(start[1]),int(start[2]))
ValueError: invalid literal for int() with base 10: ''
47.31.245.58 - - [18/Jan/2021 10:30:11] "[35m[1mPOST /book_info HTTP/1.1[0m" 500 -
47.31.245.58 - - [18/Jan/2021 10:30:41] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:30:58] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:31:25] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:31:44] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:32:01] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:33:30] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:34:18] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:34:41] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:35:10] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:37:13] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:37:40] "[37mPOST /book_info HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:37:49] "[37mPOST /book_info HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:37:58] "[37mPOST /book_info HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:38:05] "[37mPOST /book_info HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:38:13] "[37mPOST /book_info HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:38:22] "[37mPOST /book_info HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:38:28] "[37mPOST /book_info HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:38:39] "[37mPOST /book_info HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:40:11] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:40:45] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:41:45] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:48:06] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 10:49:15] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 11:02:58] "[37mPOST /issue HTTP/1.1[0m" 200 -
47.31.245.58 - - [18/Jan/2021 11:03:31] "[37mPOST /issue HTTP/1.1[0m" 200 -
